// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Async           = require("../src/Async.js");
var Block           = require("bs-platform/lib/js/block.js");
var Curry           = require("bs-platform/lib/js/curry.js");
var Respect         = require("re-respect/lib/js/src/Respect.js");
var Js_primitive    = require("bs-platform/lib/js/js_primitive.js");
var ErrorFunctions  = require("errorFunctions");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Respect_matcher = require("re-respect/lib/js/src/Respect_matcher.js");

var Dummy = Caml_exceptions.create("Async_test.Dummy");

var Dummy2 = Caml_exceptions.create("Async_test.Dummy2");

function haveMessage(expected, actual) {
  if (actual[0] === Async.JsError) {
    return Respect_matcher.equal(expected, Js_primitive.undefined_to_opt(actual[1].message));
  } else {
    return (function (param) {
        return Respect_matcher.matchFailure(actual, expected, param);
      });
  }
}

function asyncResolve(actual, cb) {
  var successCb = function (x) {
    return Curry._1(cb, /* MatchSuccess */Block.__(0, [x]));
  };
  var exnCb = function (x) {
    return Curry._1(cb, /* MatchFailure */Block.__(1, [
                  x,
                  x
                ]));
  };
  return Async.run(/* Some */[exnCb], successCb, actual);
}

function asyncThrow(actual) {
  return (function (cb) {
      var successCb = function (x) {
        return Curry._1(cb, /* MatchFailure */Block.__(1, [
                      x,
                      x
                    ]));
      };
      var exnCb = function (x) {
        return Curry._1(cb, /* MatchSuccess */Block.__(0, [x]));
      };
      return Async.run(/* Some */[exnCb], successCb, actual);
    });
}

Curry._1(Respect.Dsl[/* Async */12][/* register */3], Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "Async module", /* :: */[
          Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "return", /* :: */[
                Curry._2(Respect.Dsl[/* Async */12][/* it */1], "eventually returns the value", (function () {
                        return (function (param) {
                            return Respect_matcher.shoulda((function (param, param$1) {
                                          return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                        return Respect_matcher.equal(42, param);
                                                      }), param, param$1);
                                        }), (function (param) {
                                          return Async.$$return(42, param);
                                        }), param);
                          });
                      })),
                /* [] */0
              ]),
          /* :: */[
            Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "map", /* :: */[
                  Curry._2(Respect.Dsl[/* Async */12][/* it */1], "eventually returns the modified value", (function () {
                          return (function (param) {
                              return Respect_matcher.shoulda((function (param, param$1) {
                                            return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                          return Respect_matcher.equal(43, param);
                                                        }), param, param$1);
                                          }), (function (param) {
                                            return Async.map((function (x) {
                                                          return x + 1 | 0;
                                                        }), (function (param) {
                                                          return Async.$$return(42, param);
                                                        }), param);
                                          }), param);
                            });
                        })),
                  /* :: */[
                    Curry._2(Respect.Dsl[/* Async */12][/* it */1], "eventually returns error if mapping function throws", (function () {
                            return (function (param) {
                                return Respect_matcher.shoulda((function (param, param$1) {
                                              return Respect_matcher.$great$eq$great(asyncThrow, (function (param) {
                                                            return Respect_matcher.equal(Dummy, param);
                                                          }), param, param$1);
                                            }), (function (param) {
                                              return Async.map((function () {
                                                            throw Dummy;
                                                          }), (function (param) {
                                                            return Async.$$return(44, param);
                                                          }), param);
                                            }), param);
                              });
                          })),
                    /* [] */0
                  ]
                ]),
            /* :: */[
              Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "bind", /* :: */[
                    Curry._2(Respect.Dsl[/* Async */12][/* it */1], "eventually returns the bound value", (function () {
                            return (function (param) {
                                return Respect_matcher.shoulda((function (param, param$1) {
                                              return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                            return Respect_matcher.equal(43, param);
                                                          }), param, param$1);
                                            }), (function (param) {
                                              return Async.bind((function (x) {
                                                            var partial_arg = x + 1 | 0;
                                                            return (function (param) {
                                                                return Async.$$return(partial_arg, param);
                                                              });
                                                          }), (function (param) {
                                                            return Async.$$return(42, param);
                                                          }), param);
                                            }), param);
                              });
                          })),
                    /* :: */[
                      Curry._2(Respect.Dsl[/* Async */12][/* it */1], "eventually returns error if bound function throws", (function () {
                              return (function (param) {
                                  return Respect_matcher.shoulda((function (param, param$1) {
                                                return Respect_matcher.$great$eq$great(asyncThrow, (function (param) {
                                                              return Respect_matcher.equal(Dummy, param);
                                                            }), param, param$1);
                                              }), (function (param) {
                                                return Async.bind((function () {
                                                              throw Dummy;
                                                            }), (function (param) {
                                                              return Async.$$return(42, param);
                                                            }), param);
                                              }), param);
                                });
                            })),
                      /* [] */0
                    ]
                  ]),
              /* :: */[
                Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "from_callback", /* :: */[
                      Curry._2(Respect.Dsl[/* Async */12][/* it */1], "creates an async that succeeds", (function () {
                              return (function (param) {
                                  return Respect_matcher.shoulda((function (param, param$1) {
                                                return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                              return Respect_matcher.equal(42, param);
                                                            }), param, param$1);
                                              }), (function (param) {
                                                return Async.from_callback((function (param) {
                                                              return Curry._1(param, 42);
                                                            }), param);
                                              }), param);
                                });
                            })),
                      /* [] */0
                    ]),
                /* :: */[
                  Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "Timeout", /* :: */[
                        Curry._2(Respect.Dsl[/* Async */12][/* it */1], "fails when timeout exceeded", (function () {
                                var after = function (param) {
                                  var cb = param[0];
                                  setTimeout((function () {
                                          return Curry._1(cb, 42);
                                        }), 5);
                                  return /* () */0;
                                };
                                var partial_arg = Async.timeout(/* MilliSeconds */Block.__(0, [1]), after);
                                return (function (param) {
                                    return Respect_matcher.shoulda((function (param, param$1) {
                                                  return Respect_matcher.$great$eq$great(asyncThrow, (function (param) {
                                                                return Respect_matcher.equal(Async.Timeout, param);
                                                              }), param, param$1);
                                                }), partial_arg, param);
                                  });
                              })),
                        /* :: */[
                          Curry._2(Respect.Dsl[/* Async */12][/* it */1], "Succeeds when timeout not exceeded", (function () {
                                  var after = function (param) {
                                    var cb = param[0];
                                    setTimeout((function () {
                                            return Curry._1(cb, 42);
                                          }), 1);
                                    return /* () */0;
                                  };
                                  var partial_arg = Async.timeout(/* MilliSeconds */Block.__(0, [5]), after);
                                  return (function (param) {
                                      return Respect_matcher.shoulda((function (param, param$1) {
                                                    return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                                  return Respect_matcher.equal(42, param);
                                                                }), param, param$1);
                                                  }), partial_arg, param);
                                    });
                                })),
                          /* [] */0
                        ]
                      ]),
                  /* :: */[
                    Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "tryCatch", /* :: */[
                          Curry._2(Respect.Dsl[/* Async */12][/* it */1], "async resolve Some value", (function () {
                                  return (function (param) {
                                      return Respect_matcher.shoulda((function (param, param$1) {
                                                    return Respect_matcher.$great$eq$great(asyncThrow, (function (param) {
                                                                  return Respect_matcher.equal(Dummy2, param);
                                                                }), param, param$1);
                                                  }), (function (param) {
                                                    return Async.tryCatch((function (param) {
                                                                  if (param === Dummy) {
                                                                    return /* Some */[42];
                                                                  } else {
                                                                    return /* None */0;
                                                                  }
                                                                }), (function (param) {
                                                                  return Async.map((function () {
                                                                                throw Dummy2;
                                                                              }), (function (param) {
                                                                                return Async.$$return(43, param);
                                                                              }), param);
                                                                }), param);
                                                  }), param);
                                    });
                                })),
                          /* :: */[
                            Curry._2(Respect.Dsl[/* Async */12][/* it */1], "async throws None value", (function () {
                                    return (function (param) {
                                        return Respect_matcher.shoulda((function (param, param$1) {
                                                      return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                                    return Respect_matcher.equal(42, param);
                                                                  }), param, param$1);
                                                    }), (function (param) {
                                                      return Async.tryCatch((function (param) {
                                                                    if (param === Dummy) {
                                                                      return /* Some */[42];
                                                                    } else {
                                                                      return /* None */0;
                                                                    }
                                                                  }), (function (param) {
                                                                    return Async.map((function () {
                                                                                  throw Dummy;
                                                                                }), (function (param) {
                                                                                  return Async.$$return(43, param);
                                                                                }), param);
                                                                  }), param);
                                                    }), param);
                                      });
                                  })),
                            /* [] */0
                          ]
                        ]),
                    /* :: */[
                      Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "mapping from async js functions", /* :: */[
                            Curry._2(Respect.Dsl[/* Async */12][/* it */1], "handles JS errors nicely", (function () {
                                    var partial_arg = /* Some */["dummy"];
                                    var partial_arg$1 = function (param) {
                                      return haveMessage(partial_arg, param);
                                    };
                                    var partial_arg$2 = function (param, param$1) {
                                      return Respect_matcher.$great$eq$great(asyncThrow, partial_arg$1, param, param$1);
                                    };
                                    return (function (param) {
                                        return Respect_matcher.shoulda(partial_arg$2, (function (param) {
                                                      return Async.from_js((function (param) {
                                                                    ErrorFunctions.asyncThrowingFunction(42, param);
                                                                    return /* () */0;
                                                                  }), param);
                                                    }), param);
                                      });
                                  })),
                            /* :: */[
                              Curry._2(Respect.Dsl[/* Async */12][/* it */1], "also handles when no error occues", (function () {
                                      return (function (param) {
                                          return Respect_matcher.shoulda((function (param, param$1) {
                                                        return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                                      return Respect_matcher.equal(42, param);
                                                                    }), param, param$1);
                                                      }), (function (param) {
                                                        return Async.from_js((function (param) {
                                                                      ErrorFunctions.asyncSucceedingFunction(42, param);
                                                                      return /* () */0;
                                                                    }), param);
                                                      }), param);
                                        });
                                    })),
                              /* [] */0
                            ]
                          ]),
                      /* :: */[
                        Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "once", /* :: */[
                              Curry._2(Respect.Dsl[/* Async */12][/* it */1], "only calls the underlying function once, we hook up functions before resolution", (function () {
                                      var start = [0];
                                      var f = function (param) {
                                        var cb = param[0];
                                        start[0] = start[0] + 1 | 0;
                                        setTimeout((function () {
                                                return Curry._1(cb, start[0]);
                                              }), 10);
                                        return /* () */0;
                                      };
                                      var f$1 = Async.once(f);
                                      return (function (param) {
                                          return Respect_matcher.shoulda((function (param, param$1) {
                                                        return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                                      return Respect_matcher.equal(1, param);
                                                                    }), param, param$1);
                                                      }), (function (param) {
                                                        return Async.bind((function () {
                                                                      return f$1;
                                                                    }), f$1, param);
                                                      }), param);
                                        });
                                    })),
                              /* :: */[
                                Curry._2(Respect.Dsl[/* Async */12][/* it */1], "Only calls the underlying function onde, we hook up functions after resolution", (function () {
                                        var start = [0];
                                        var f = function (param) {
                                          var cb = param[0];
                                          start[0] = start[0] + 1 | 0;
                                          setTimeout((function () {
                                                  return Curry._1(cb, start[0]);
                                                }), 0);
                                          return /* () */0;
                                        };
                                        var f$1 = Async.once(f);
                                        return (function (param) {
                                            return Respect_matcher.shoulda((function (param, param$1) {
                                                          return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                                        return Respect_matcher.equal(1, param);
                                                                      }), param, param$1);
                                                        }), (function (param) {
                                                          return Async.bind((function () {
                                                                        return f$1;
                                                                      }), (function (param) {
                                                                        return Async.bind((function () {
                                                                                      return f$1;
                                                                                    }), (function (param) {
                                                                                      var delay = 10;
                                                                                      var param$1 = param;
                                                                                      setTimeout(param$1[0], delay);
                                                                                      return /* () */0;
                                                                                    }), param);
                                                                      }), param);
                                                        }), param);
                                          });
                                      })),
                                /* [] */0
                              ]
                            ]),
                        /* :: */[
                          Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "iter", /* :: */[
                                Curry._2(Respect.Dsl[/* Async */12][/* it */1], "calls the inline function", (function (_, don) {
                                        var x = [42];
                                        var partial_arg = Async.iter((function (y) {
                                                x[0] = x[0] + y | 0;
                                                return /* () */0;
                                              }));
                                        return Async.run(/* None */0, (function () {
                                                      var partial_arg = x[0];
                                                      return (function (param) {
                                                                  return Respect_matcher.shoulda((function (param) {
                                                                                return Respect_matcher.equal(43, param);
                                                                              }), partial_arg, param);
                                                                })(don);
                                                    }), (function (param) {
                                                      return partial_arg((function (param) {
                                                                    return Async.$$return(1, param);
                                                                  }), param);
                                                    }));
                                      })),
                                /* :: */[
                                  Curry._2(Respect.Dsl[/* Async */12][/* it */1], "Returns the original value", (function () {
                                          var x = [42];
                                          var partial_arg = Async.iter((function (y) {
                                                  x[0] = x[0] + y | 0;
                                                  return /* () */0;
                                                }));
                                          var partial_arg$1 = function (param) {
                                            return partial_arg((function (param) {
                                                          return Async.$$return(1, param);
                                                        }), param);
                                          };
                                          return (function (param) {
                                              return Respect_matcher.shoulda((function (param, param$1) {
                                                            return Respect_matcher.$great$eq$great(asyncResolve, (function (param) {
                                                                          return Respect_matcher.equal(1, param);
                                                                        }), param, param$1);
                                                          }), partial_arg$1, param);
                                            });
                                        })),
                                  /* [] */0
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]));

exports.Dummy        = Dummy;
exports.Dummy2       = Dummy2;
exports.haveMessage  = haveMessage;
exports.asyncResolve = asyncResolve;
exports.asyncThrow   = asyncThrow;
/*  Not a pure module */
